### ISSUE TITLE
Connection label does not work

### ISSUE THREAD

**Issue by rzaharenkov** [zapier/zapier-platform-example-app-oauth2#12]
I am testing my OAuth2 authentication and everything goes smoothly except connection label. I am able to connect account and it returns 'Success!' when I test the connection. I see on my end that `/me` is executed and replies with JSON:

```
{ "username": "some@email.com" }
```

I have a default connection label configuration in my application:

```
  // assuming "username" is a key returned from the test
  connectionLabel: '{{username}}'
```

But I am getting label `{{username}}` on the UI, so username is not substituted for some reason.

![connected accounts zapier 2018-05-25 13-02-25](https://user-images.githubusercontent.com/27693283/40539006-0a817ca0-601c-11e8-8a40-26b78471eaee.png)

**Comment by BrunoBernardino** [comment]
Hi @rzaharenkov thank you so much for reporting this!

At a glance, it seems we `return response` instead of `return z.JSON.parse(response.content)` in https://github.com/zapier/zapier-platform-example-app-oauth2/blob/master/authentication.js#L71 so we're not identifying the values to then parse in the connection label.

Can you try please that?

**Comment by rzaharenkov** [comment]
@BrunoBernardino, thank you for a quick reply.

I've also tried to return `JSON.parse(response)` but it failed so looks like response is an object not a string:

![edit a step zapier 2018-05-25 13-24-36](https://user-images.githubusercontent.com/27693283/40539940-fee4d3b2-601e-11e8-90bf-62c6810c7209.png)

**Comment by BrunoBernardino** [comment]
What about parsing `response.content` instead of `response`?

**Comment by rzaharenkov** [comment]
Wow! It works, thanks!

**Comment by BrunoBernardino** [comment]
Will still leave this open as we need to fix that in the code.
