### ISSUE TITLE
Zapier refresh call fails against Cognito

### ISSUE THREAD

**Issue by chucksspencer** [zapier/zapier-platform-example-app-oauth2#15]
Hi there. We've created a zap app that authenticate via Cognito. The initial flow works fine but the Refresh token call always fails with a 400 {"error":"invalid_client"}. Our code implementation:

```js
const refreshAccessToken = (z, bundle) => {

  const promise = z.request('${Settings.current.authUrl}/oauth2/token', {
    method: 'POST',
    body: {
      refresh_token: bundle.authData.refresh_token,
      client_id: Settings.current.clientId,
      client_secret: Settings.current.clientSecret,
      grant_type: 'refresh_token'
    },
    headers: {
      'content-type': 'application/x-www-form-urlencoded'
    }
  });

  return promise.then((response) => {
    if (response.status !== 200) {
      throw new Error('Unable to fetch access token: ' + response.content);
    }

    const result = JSON.parse(response.content);

    const auth_fields = {
      access_token: result.access_token
    }
    if (result.refresh_token) {
      auth_fields.refresh_token = result.refresh_token
    }
    return auth_fields
  })
  .catch((err) => {
    Logger.error(err, z);
    throw err;
  });
};
```

We have verified that the refresh token value is present, and that the client ID and client secret are correct.

**Comment by chucksspencer** [comment]
I figured out the reason for this. Cognito is expecting Basic auth with the encoded clientid/secret, which this code adds. However the `includeBearerToken` code configured for the `beforeRequest` hook was overwriting that Auth header with the Bearer token. I fixed it by nulling out the access token before making the call.

`  const encodedBasicAuth = Buffer.from('${Settings.current.clientId}:${Settings.current.clientSecret}').toString('base64');
  bundle.authData.access_token = null;

  const promise = z.request('${Settings.current.authUrl}/oauth2/token', {
    method: 'POST',
    body: {
      refresh_token: bundle.authData.refresh_token,
      client_id: Settings.current.clientId,
      grant_type: 'refresh_token'
    },
    headers: {
      'content-type': 'application/x-www-form-urlencoded',
      'Authorization': `Basic ${encodedBasicAuth}`
    }
  });`

Not sure if this is something you want to add to this sample, but hopefully it'll help someone else out down the road.

**Comment by RobertUpchurch** [comment]
For anyone here a few years later: This configuration worked for me:

```javascript
const encodedBasicAuth = Buffer.from(`${process.env.CLIENT_ID}:${process.env.CLIENT_SECRET}`).toString('base64');

const options = {
  url: 'https://{your domain}/oauth2/token',
  method: 'POST',
  headers: {
    'content-type': 'application/x-www-form-urlencoded',
    'accept': 'application/json',
    'Authorization': `Basic ${encodedBasicAuth}`
  },
  params: {
    grant_type: 'refresh_token'
  },
  body: {
    refresh_token: bundle.authData.refresh_token,
    client_id: process.env.CLIENT_ID
  }
}

return z.request(options)
  .then((response) => {
    response.throwForStatus();
    const results = response.json;

    return results;
  });
```
