### ISSUE TITLE
Second token refresh fails

### ISSUE THREAD

**Issue by johnpan** [zapier/zapier-platform-example-app-oauth2#6]
https://github.com/zapier/zapier-platform-example-app-oauth2/blob/b231ea551bc6c016d1a40516f57a3816255fae23/authentication.js#L52

refreshAccessToken method, should return both refresh_token and access_token values to be stored back in bundle, exaclty like getAccessToken method does. I tried that with Laravel Passport which failed to auth in the second refresh since it the tokens pair would not match any more.

**Comment by FokkeZB** [comment]
@johnpan thanks for the feedback!

Do you mean that some APIs refresh the `refresh_token` as well when we refresh the `access_token` using the current `refresh_token`?

In that case, yes, that method should return both. I'm not sure if that's typical behaviour we see, although it couldn't hurt to update the example with that change.

Up for a PR?

**Comment by johnpan** [comment]
Hi @FokkeZB , thanks for your reply, sure, let's do it
